version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: task_manager_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: task_manager_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/taskdb
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: task_manager_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
