services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/tasks.db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend  # Keep this dependency so frontend waits for backend

volumes:
  sqlite_data:
