- name: Theme 02 - CIS Hardening (Registry Method)
  hosts: rocky,windows
  become: yes

  tasks:
    # SYSTEM ADMINISTRATION
    - name: Install auditd on Rocky
      ansible.builtin.yum:
        name: audit
        state: present
      when: ansible_os_family == 'Rocky'

    - name: Configure Windows Event Forwarding
      ansible.windows.win_eventlog:
        name: ForwardedEvents
        log_mode: auto
        maximum_size_in_bytes: 104857600

    # SYSTEM HARDENING
    - name: Disable SSH Root Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSHD
      when: ansible_os_family == 'Rocky'

    # AD GPO HARDENING (Using Registry Edits)
    - name: Set Account Lockout Policy (LockoutBadCount)
      ansible.windows.win_regedit:
        path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
        name: "LockoutBadCount"
        data: 5
        type: dword

    - name: Set Account Lockout Policy (ResetLockoutCount)
      ansible.windows.win_regedit:
        path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
        name: "ResetLockoutCount"
        data: 15
        type: dword

    - name: Disable SMBv1
      ansible.windows.win_regedit:
        path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanmanServer\\Parameters"
        name: "SMB1"
        data: 0
        type: dword
