- name: Theme 01 - Unified Configuration Management
  hosts: windows,rocky
  become: yes
  vars:
    standard_timezone: America/New_York
    allowed_ips: 192.168.1.0/24

  tasks:
    # SYSTEM ADMINISTRATION (2 elements)
    - name: Set timezone on Rocky
      ansible.builtin.timezone:
        name: "{{ standard_timezone }}"
      when: ansible_os_family == 'Rocky'

    - name: Configure Windows Time Service
      ansible.windows.win_service:
        name: W32Time
        start_mode: auto
        state: started
      when: ansible_os_family == 'Windows'

    # SYSTEM HARDENING (2 elements)
    - name: Configure firewalld on Rocky
      ansible.posix.firewalld:
        zone: public
        permanent: true
        source: "{{ allowed_ips }}"
        state: enabled
      when: ansible_os_family == 'Rocky'

    - name: Enable Windows Defender Firewall
      ansible.windows.win_firewall:
        profiles:
          - Domain
          - Private
          - Public
        state: enabled

    # AD GPO HARDENING (3 elements)
    - name: Enforce Password Policy
      community.windows.win_gpo:
        name: "Password Policy Enforcement"
        state: present
        policy_path: "Windows Settings\\Security Settings\\Account Policies\\Password Policy"
        policy_entries:
          MinimumPasswordLength: 12
          PasswordComplexity: 1

    - name: Restrict User Rights
      community.windows.win_gpo:
        name: "User Rights Assignment"
        policy_path: "Windows Settings\\Security Settings\\Local Policies\\User Rights Assignment"
        policy_entries:
          SeInteractiveLogonRight: []
          SeRemoteInteractiveLogonRight: ["Administrators"]

    - name: Deploy Security Templates
      ansible.windows.win_security_policy:
        section: System Access
        minimum_password_age: 1
        maximum_password_age: 60
