- name: Theme 02 - CIS Hardening
  hosts: rocky,windows
  become: yes

  tasks:
    # SYSTEM ADMINISTRATION
    - name: Install auditd on Rocky
      ansible.builtin.yum:
        name: audit
        state: present
      when: ansible_os_family == 'Rocky'

    - name: Configure Windows Event Forwarding
      ansible.windows.win_eventlog:
        name: ForwardedEvents
        log_mode: auto
        maximum_size_in_bytes: 104857600

    # SYSTEM HARDENING
    - name: Disable SSH Root Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSHD
      when: ansible_os_family == 'Rocky'

    - name: Set Account Lockout Policy
      community.windows.win_gpo:
        name: "Account Lockout Policy"
        policy_path: "Windows Settings\Security Settings\Account Policies\Account Lockout Policy"
        policy_entries:
          LockoutBadCount: 5
          ResetLockoutCount: 15

    # AD GPO HARDENING
    - name: Disable SMBv1
      community.windows.win_gpo:
        name: "SMB Security Settings"
        policy_path: "Windows Settings\Security Settings\Local Policies\Security Options"
        policy_entries:
          NetworkSecurity_LANManagerAuthenticationLevel: 3
